// This file was auto-generated by SceneListCheck!

public enum Scenes 
{
	scene_tilemap = 0,
	scene_beginning = 1,
	scene_courthouse = 2,
	scene_panda = 3,
	scene_unicorn = 4,
	scene_owl = 5,
	scene_eylias = 6,
	scene_david = 7,
	scene_random = 8
}

